Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -16,9 +16,13 @@ phases:
       - sleep 10
 
       # Check Sonar Quality Gate and save result
-      - quality_status=$(curl -s -u 0a6069d5d0e188cf7ee87bad3bbdbfd7eeb1ae05: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=awsproject01" | tee sonar-report.json | jq -r '.projectStatus.status')
-      - echo "SonarCloud analysis status is $quality_status"
-      - if [ "$quality_status" = "ERROR" ]; then echo "❌ Quality Gate failed" && exit 1; fi
+      - |
+        quality_status=$(curl -s -u 0a6069d5d0e188cf7ee87bad3bbdbfd7eeb1ae05: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=awsproject01" | tee sonar-report.json | jq -r '.projectStatus.status')
+        echo "SonarCloud analysis status is $quality_status"
+        if [ "$quality_status" = "ERROR" ]; then
+          echo "Quality Gate failed ❌"
+          exit 1
+        fi
 
       # Run Snyk SCA (Software Composition Analysis) - Non-blocking
       - echo "🔑 Authenticating with Snyk"
